feat: customize Marker using Composable
googlemaps/android-maps-compose pull request #355
Opened 2023-07-28 15:19 UTC by mosmb

- Create a Marker Composable that accepts a Composable content
- Update BasicMapActivity to show the Composable Marker
---

- [X] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [X] Appropriate docs were updated (if necessary)

Fixes #41  🦕

2023-07-31 14:21 UTC, mosmb commented on maps-compose/src/main/java/com/google/maps/android/compose/Marker.kt
> +public fun Marker(
100% agree on this, there are already a lot of Composable overloading for `Marker`.
Also, it's not convenient to use and distinguish inside the IDE

2023-07-31 14:21 UTC, mosmb commented on maps-compose/src/main/java/com/google/maps/android/compose/Marker.kt
> + * A composable for a marker on the map.
Will update it

2023-07-31 14:29 UTC, mosmb commented on maps-compose/src/main/java/com/google/maps/android/compose/Marker.kt
> +public fun Marker(
I was thinking about it and yes.
It makes sense as this is the thing people will tend to search for when using `maps-compose`

2023-07-31 15:02 UTC, mosmb commented
@kikoso 
I updated based on what you suggest.
Feel free to suggest any other changes that you may think of :)

2023-08-01 15:49 UTC, mosmb commented
@kikoso 
Feel free to tell me if you see other things to edit

2023-08-03 06:55 UTC, mosmb commented
@kikoso 
Yep I added the API key as a secret in my repository, so I think it should work

2023-08-03 13:41 UTC, mosmb commented
@kikoso Tests seem to fail because of the API key
I added a secret `ACTIONS_API_KEY ` to my rep but doesn't seem to work though

2023-08-07 12:22 UTC, mosmb commented
@kikoso 
Any news for this PR to be able to be merged?

2023-08-10 07:32 UTC, mosmb commented
@kikoso Ok! Thank you for the information!

2023-08-12 00:09 UTC, wangela requested changes
Thank you for contributing this highly requested feature, @mosmb! Although the github action can't access the secrets to run tests on GitHub, would you still please add tests for the new functionality to keep our code coverage even? We'll be able to merge this PR when that task is done.

2023-08-15 09:02 UTC, mosmb commented
Thank you @wangela for your feedback! 
What kind of test do you expect? 
As I can see, there's no test for now for `Marker`, except one testing that a state must not be reused.
Do you expect to do the same test but with `MarkerComposable`?

2023-08-17 17:32 UTC, wangela approved these changes

2023-08-17 18:03 UTC, merged

2023-08-30 15:42 UTC, WonderCsabo commented
@mosmb checking out your code, i stumbled upon [this](https://github.com/googlemaps/android-maps-compose/pull/355/files#diff-3f37360306c965afa0b67bbcce39c6d17ecb9db7fc16e6c6b8fb7a5a0bce32d9R47) line:

```kotlin
composeView.draw(fakeCanvas)
```

I was wondering, why is this needed?

2023-08-31 08:55 UTC, mosmb commented
@WonderCsabo In some cases, the `ComposeView` will not trigger the draw of its node. So in order to force that and not having a `Composable` that is not being drawn, we draw an empty canvas into the `ComposeView` to force it to enter into the drawing phase.
It's kinda of a hack but it works.
In Compose `1.5.0`, they added some utility method to `Picture` to be able to draw `Composable` into bitmaps. But as this library is not based on this version of Compose yet, we stick with this hack

2023-09-01 07:16 UTC, WonderCsabo commented
@mosmb thanks for the info. Good to know there will be an official method to do this. Now i see it in the [docs](https://developer.android.com/jetpack/compose/graphics/draw/modifiers#composable-to-bitmap).