docs: added recomposition sample
googlemaps/android-maps-compose pull request #448
Opened 2023-10-27 14:53 UTC by kikoso

This PR adds a recomposition sample, to showcase how to remove or add markers using a remember variable and recomposition.

https://github.com/googlemaps/android-maps-compose/assets/903097/098a6a95-4a24-45e0-b5e8-1acfa3b144ce

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [X] Appropriate docs were updated (if necessary)

Fixes #442, #91, #403 🦕

2023-11-17 17:41 UTC, wangela requested changes
Let's also add to the "Drawing on a map" section of the README about how to update the state of composables that have been added to the map. Can just link to this activity if the code snippet gets too long.

2023-12-09 06:35 UTC, wangela approved these changes

2023-12-09 06:35 UTC, merged

2023-12-09 10:48 UTC, bubenheimer commented
@wangela May I ask why these commits were merged without further discussion? I pointed out a problem, yet my comments were ignored. This action does not promote a healthy open-source culture for this project. I will need to assess the relevance of future contributions from my side.

I respect that there may be differences in opinion, but there needs to be discussion to resolve those. Apart from my prior pointers: the API provides a dedicated function [`rememberMarkerState()`](https://googlemaps.github.io/android-maps-compose/maps-compose/com.google.maps.android.compose/remember-marker-state.html) to maintain `MarkerState`. It is unclear why the project documentation and samples would promote a different approach that does not actually remember the state object itself, but continuously recreates it.

I tried to voice my concerns in a helpful, professional manner, but perhaps I was too subtle? I would not go through the effort of commenting unless I see a strong need for changes.

The present action suggests that I and other users of this project will need to find alternative means to restore and maintain sufficient API quality for our own projects in the face of ongoing regressions since @arriolac's departure. For example the present documentation regression, as well as #466 and #347. I appreciate that #347 was reverted after I voiced my concerns, but this PR points in a different direction. The existence of #466 should have rung alarm bells.

The end result of all this is a necessity for private forks. I do not see a viable alternative, unless there are changes to how this project is managed. Seeing #347 gave me a scare (its problems should have been caught in code reviews, and it even required changing a test to make it pass), so I started to review every PR personally in an effort to catch serious regressions early, but now I am finding that my input is ignored. Private forks are expensive to maintain for independent devs like myself, so I wish this could be resolved in a different manner.

2023-12-10 13:01 UTC, bubenheimer commented
@kikoso I'm not sure what you mean about "no comment" on this PR. I started a code review right here in this PR soon after your initial commit, with 4 comments total. You did not respond to the concerns that I brought up in the context of the review. It's all still up there. Please clarify.

2023-12-10 13:10 UTC, bubenheimer commented
As for whether to use `rememberMarkerState()` specifically: it's not essential, it just `remembers` 'MarkerState'.

What I'm saying is that it does not make sense to recreate `MarkerState` on recomposition, and `remember` a separate `mutableStateOf()` for the location. `MarkerState` is the relevant state object here and needs to be the one to be remembered. `MarkerState` encapsulates more than just location.

The merged commit demonstrates a bad pattern. I hope it can be unmerged.

2023-12-10 16:51 UTC, bubenheimer commented on app/src/main/java/com/google/maps/android/compose/RecompositionActivity.kt
> +        val singaporeState = MarkerState(position = location)
`MarkerState.position` is a var with a public setter and a `mutableStateOf` behind it, and it is observed for changes by `Marker()` machinery. So it is not necessary to keep a separate remembered `mutableStateOf` to track position changes, or to recreate MarkerState on every recomposition.
Consider this instead:
```
val singaporeState = remember { MarkerState(singapore) }
```
Then update via:

```
singaporeState.position = when (randomValue) {
    0 -> singapore
    1 -> singapore2
    2 -> singapore3
    else -> singapore
```

2023-12-10 17:00 UTC, bubenheimer commented on app/src/main/java/com/google/maps/android/compose/RecompositionActivity.kt
> +        val singaporeState = MarkerState(position = location)
@wangela @kikoso if this pattern does not work then there has been a regression that needs to be fixed. Various recently filed issues and my own testing suggest that this is the case. The pattern used to work flawlessly and is the way the API is intended to be used; it's described at https://github.com/androidx/androidx/blob/androidx-main/compose/docs/compose-api-guidelines.md#hoisted-state-types and subsequent sections.

Recreating MarkerState on every recomposition is akin to the following, which the IDE will tell you is missing 'remember':
```
val state = mutableStateOf(1)
```

2023-12-10 17:00 UTC, bubenheimer commented on app/src/main/java/com/google/maps/android/compose/RecompositionActivity.kt
> +        val singaporeState = MarkerState(position = location)
@wangela @kikoso FYI: the regression (if it is just a single one) was introduced in 2.14.1

2023-12-10 17:01 UTC, bubenheimer commented on README.md
> +val singaporeState = MarkerState(position = location)
Same concerns as in sample

2023-12-10 17:15 UTC, bubenheimer commented
Thanks @kikoso, I must have missed clicking the button initially, and I think the button may have stopped working later after force push & merge/closure. I've added my prior comments as regular comments now, to show what I had in mind. I seem no longer able to start a review on a closed PR.

My sincere apologies for the noise & waste of time on your end.

Would it be possible to change the sample & docs still? I don't think there is any valid use case where one would not want to retain MarkerState across recompositions.

That said, there certainly is a common need to sync MarkerState with information that is kept outside Compose. This would be a slightly larger example. An important example, though.