docs: improved recomposition sample
googlemaps/android-maps-compose pull request #475
Opened 2023-12-14 16:36 UTC by kikoso

This PR changes the recomposition sample to showcase a better usage of location within the MarkerState.

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [X] Appropriate docs were updated (if necessary)

Fixes #448 🦕

2023-12-14 17:35 UTC, bubenheimer reviewed
@kikoso Thank you for revisiting this. The sample code looks good to me. I've added a couple comments to try and make the documentation easier to grasp.

2023-12-14 17:35 UTC, bubenheimer commented on README.md
> +val singaporeState = remember { MarkerState(singapore) }
I suggest a named parameter for clarity corresponding to the textual explanation below referencing `position`:

```
val singaporeState = remember { MarkerState(position = singapore) }
```

2023-12-14 17:35 UTC, bubenheimer commented on README.md
>  have a mutable state variable:
Perhaps say "To achieve recomposition you can set mutable properties of state objects:"

2023-12-14 17:35 UTC, bubenheimer commented on README.md
> +In the example above, when the `position` attribute in the MarkerState changes, the recomposition will be triggered.
How about adding something like this to make it clear:

```
LaunchedEffect(Unit) {
    repeat(10) {
        delay(5.seconds)
        val old = singaporeState.position
        singaporeState.position = LatLng(old.latitude + 1.0, old.longitude + 2.0)
    }
}
```

"In the example above, recomposition occurs as `MarkerState.position` is updated with different values over time", shifting the Marker around the screen.

2023-12-15 09:48 UTC, bubenheimer requested changes

2023-12-15 09:48 UTC, bubenheimer commented on README.md
> +LaunchedEffect(Unit) {
I think you accidentally removed the Marker Composable

2023-12-15 09:55 UTC, bubenheimer approved these changes
Looks great, thanks again

2023-12-15 17:21 UTC, wangela requested changes

2023-12-15 17:21 UTC, wangela commented on app/src/main/java/com/google/maps/android/compose/RecompositionActivity.kt
> +        val singaporeState = remember { MarkerState(position = singapore) }
For general applicability, let's rename this to `markerState`

2023-12-20 10:07 UTC, wangela requested changes

2024-01-15 07:36 UTC, bubenheimer commented on README.md
> +val markerState = remember { MarkerState(position = singapore) }
Actually, how about `rememberMarkerState()` instead to retain state across configuration changes? (It uses `rememberSaveable()` behind the scenes.)
```suggestion
val markerState = rememberMarkerState(position = singapore)
```

2024-01-15 07:42 UTC, bubenheimer commented on app/src/main/java/com/google/maps/android/compose/RecompositionActivity.kt
> +        val markerState = remember { MarkerState(position = singapore) }
Same change to `rememberMarkerState()` here, to retain position across configuration changes.
```suggestion
        val markerState = rememberMarkerState(position = singapore)
```

2024-01-22 22:26 UTC, wangela commented on README.md
> +val singaporeState = remember { MarkerState(position = singapore) }
This still looks like singaporeState to me. Did you push the commit with the change?

2024-01-22 22:27 UTC, wangela approved these changes

2024-01-22 22:28 UTC, merged