chore: set doc PRs on auto-merge
googlemaps/android-maps-compose pull request #650
Opened 2024-11-22 09:02 UTC by kikoso

The following PR will set the PRs from googlemaps-bot on AutoMerge.

2024-11-22 16:25 UTC, dkhawk commented on .github/workflows/auto-merge-doc.yml
> +# Copyright 2022 Google LLC
nit: 2024

2024-11-22 16:26 UTC, dkhawk approved these changes

2024-11-22 19:50 UTC, wangela requested changes
Would [merge-on-green](https://github.com/googleapis/repo-automation-bots/tree/main/packages/merge-on-green) (a Google Cloud-authored bot) be helpful here? Could we apply the `automerge` label only to Docs PRs generated by the [docs.yml](https://github.com/googlemaps/android-maps-compose/blob/main/.github/workflows/docs.yml) workflow instead of all PRs opened by googlemaps-bot? Unless you are thinking that you also want to automerge dependabot PRs too?

2024-11-26 17:07 UTC, dkhawk approved these changes

2024-11-26 17:08 UTC, dkhawk approved these changes

2024-11-26 17:10 UTC, merged